handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    stream: ext://sys.stdout

  app_monitor:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    level: DEBUG
    filename: log/app_monitor.log
    maxBytes: 10485760
    backupCount: 20

loggers:
  app_monitor:
    level: DEBUG
    handlers:
      - app_monitor
